                                Summary
                                
1. Installed and loaded the required libraries.
2. Loaded and normalized the MNIST dataset.
3. Built the keras model with sequential class.
4. Compiled the model.
5. Trained the model.
6. Predicted the accuracy as 97% using the model.
7. Prepared confusion matrix.

In [4]:
! pip install tensorflow numpy mnist

In [5]:
import numpy as np
import mnist
from tensorflow import keras

In [6]:
# Load MNIST dataset

train_images = mnist.train_images()
train_labels = mnist.train_labels()

print(train_images.shape) # (60000, 28, 28)
print(train_labels.shape) # (60000,)

(60000, 28, 28)
(60000,)


In [7]:
# Normalize the dataset

import numpy as np
import mnist

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

print(train_images.shape) # (60000, 28, 28, 1)
print(test_images.shape)  # (10000, 28, 28, 1)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [9]:
# Keras model built using sequential class

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

num_filters = 8
filter_size = 3
pool_size = 2

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

In [10]:
# Model compilation

model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [11]:
# Model Training

import mnist

train_labels = mnist.train_labels()
print(train_labels[0]) # 5

5


In [12]:
# Convert class integers to array of vectors

from tensorflow.keras.utils import to_categorical

model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.3652 - accuracy: 0.8941 - val_loss: 0.2169 - val_accuracy: 0.9388
Epoch 2/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1874 - accuracy: 0.9460 - val_loss: 0.1424 - val_accuracy: 0.9594
Epoch 3/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1322 - accuracy: 0.9621 - val_loss: 0.1156 - val_accuracy: 0.9657


In [13]:
# Save Model

model.save_weights('cnn.h5')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

num_filters = 8
filter_size = 3
pool_size = 2

# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Load the model's saved weights.
model.load_weights('cnn.h5')


In [16]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# True labels
true_label=np.argmax(predictions, axis=1)
print(true_label) # [7, 2, 1, 0, 4]

# Prediction labels
test_label=test_labels[:5]
print(test_label) # [7, 2, 1, 0, 4]

1/1 [==============================] - 0s 54ms/step
[9 6 0 6 6]
[7 2 1 0 4]


In [21]:
! pip install torchvision

     |████████████████████████████████| 1.3MB 2.9MB/s eta 0:00:01


In [22]:
import torch 
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as trans

# initialize a confusion matrix with 0s
confusion_matrix = torch.zeros(10, 10, dtype=torch.int32)
print(confusion_matrix.numpy())

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [35]:
# Confusion Matrix

from sklearn.metrics import confusion_matrix

# simply call the confusion_matrix function to build a confusion matrix
cm = confusion_matrix(true_label, true_label)
print(cm)

[[1 0 0]
 [0 3 0]
 [0 0 1]]
